Create header
Aidan-bn/Portfolio pull request #1
Opened 2022-05-30 12:48 UTC by Aidan-bn

# Portfolio: Setup and Mobile Version Skeleton 

This is a simple web development project for Microverse created using simple HTML (Hyper Text Mark-up Language) and CSS (Cascading Style Sheet)

## Built With

Major languages: HTML and CSS

[Live Demo Link] (https://livedemo.com)

## Getting Started
To get a local copy up and running follow these simple example steps.

👤 **Author1**

- GitHub: [@aidan-bn](https://github.com/aidan-bn)
- Twitter: [@aidan-bn](https://twitter.com/aidan-bn)
- LinkedIn: [Aidan-bn](https://linkedin.com/in/aidan-bn)

2022-05-30 13:14 UTC, t-yanick reviewed
Hi @Aidan-bn, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have a professional readme file. Checkout this [template](https://github.com/microverseinc/readme-template) and adapt it to your project. Replace all the information in the various sections of the template with information pertaining to your poject.  This will make your readme file more informative and professional. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_Invalid Code Review Request **does not count** into the code reviews limit._

2022-05-30 14:42 UTC, micheaol requested changes
Hi @Aidan-bn , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## TO HIGHLIGHT: 
- Your project is professional 💯 
- Your repo is professional 💯 
- Well structured files 💯 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-05-30 14:42 UTC, micheaol commented on index.html
> +               <li class="listitems">Contact</li>
There should be a hamburger button on the right and has a `nav` tag like the code below:

````
<nav>
     hamburger button
</nav>
````

Your Implementation | Figma Design
:---:|:---:
![image](https://user-images.githubusercontent.com/10332499/171014541-342b5d4b-30ff-4f7a-b4ce-03ffe52425e0.png) | ![image](https://user-images.githubusercontent.com/10332499/171014857-f3f79f23-e4d5-43e0-9159-18f65a47faf7.png)

2022-05-30 14:42 UTC, micheaol commented on index.html
> +        <section class="headline">
Please ensure to remove the `headline section` from the header. Please see the code below:

````
<header>
       <nav>
  ------------------------------
        </nav>
</header>

<section>
        ------------------headlines----------------
</section>








````

2022-05-30 14:42 UTC, micheaol commented on index.html
> +                </div>
Please ensure that you stick to the design of any of the templates of your choice as much as possible (e.g. font, colors, images, tests, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).

Your Implementation | Figma Design
:---:|:---:
![image](https://user-images.githubusercontent.com/10332499/171015349-fdbde7fb-ec34-40f3-9fbc-48001ab30546.png) | ![image](https://user-images.githubusercontent.com/10332499/171015276-22adfe00-2955-4d15-a472-7e679083cdee.png)

2022-05-30 14:42 UTC, micheaol commented on styles.css
> +}
Please ensure that the `headline content` is aligned with flexbox according to the project requirement.

2022-06-01 16:20 UTC, tufoinnkuo10 commented on index.html
> +        </nav>
- [ ] like the previous reviewer mentioned please only the hamburger icon should be inside the nav tag and not the logo.
```
<header>
    <p>logo</p>
     <nav>
           hamburger button
   </nav>
</header>
```

2022-06-01 16:27 UTC, tufoinnkuo10 commented on index.html
> +                        <li class="socialists"><a href="https://angellist.com/aidan-bn"><i class="fa fa-angellist"></i></a></li>
- [ ] please like the previous reviewer mentioned you should follow same figma font of margin, colors, font weight and sizes. also your social icons are different from that of the figma design. 
your design
![Screenshot (95)_LI](https://user-images.githubusercontent.com/65298048/171453787-41443101-9c3d-4215-aef0-072b23876ed0.jpg)
figma design
![Screenshot (96)_LI](https://user-images.githubusercontent.com/65298048/171453838-09d076fa-8fa9-4b78-8707-70bb9e79e3ac.jpg)

2022-06-03 11:05 UTC, KayLemba approved these changes
# STATUS: APPROVED :green_circle: :clap: 

Hello  @Aidan-bn     , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

HIGHLIGHTS:

- Your project is professional 
- Your repo is professional 
- Well structured files 


Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

[OPTIONAL] Kindly add a screenshot to your README file showing your webpage user Interface. You can use extentions like fireshot to capturer the entire page.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-03 19:39 UTC, merged